### ISSUE TITLE
When I use this project to simulate cloth, it will drectly flashback.

### ISSUE THREAD

**Issue by ZYang6263** [MercuryGH/pd-with-gpu#1]
I open the gui and transform to simulate cloth, but when I ckick the Load instance button, flashback is happen.
![截图 2023-12-09 12-03-23](https://github.com/MercuryGH/pd-with-gpu/assets/50876451/e7888fc3-96f7-4613-9760-fef8544868a0)

![截图 2023-12-09 12-06-37](https://github.com/MercuryGH/pd-with-gpu/assets/50876451/6579cfb0-25e3-4f5d-b09f-28e5a2730f2d)

**Comment by MercuryGH** [comment]
This project is simple and for demo only. I feel sorry for any potential bugs. 
Could you provide more information about this crash? It works well with my computer. You can use a debugger to find out the code that trigger this crash, and show it to me.

**Comment by ZYang6263** [comment]
Thanks for your reply! 
I recompiled this project, now the crash problem is gone.
